2023-11-05 13:26:48,302 - kedro.pipeline.node - ERROR - Node 'train_node: train([train_X,train_Y,test_X,test_Y,val_X,val_Y,params:model_params]) -> [model_output]' failed with error:
'numpy.ndarray' object has no attribute 'columns'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\anaconda3\envs\asi-03_env\Scripts\kedro.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\cli\cli.py", line 211, in main
    cli_collection()
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\cli\cli.py", line 139, in main
    super().main(
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\cli\project.py", line 453, in run
    session.run(
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\session\session.py", line 436, in run
    run_result = runner.run(
                 ^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py", line 103, in run
    self._run(pipeline, catalog, hook_manager, session_id)
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\sequential_runner.py", line 70, in _run
    run_node(node, catalog, hook_manager, self._is_async, session_id)
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py", line 331, in run_node
    node = _run_node_sequential(node, catalog, hook_manager, session_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py", line 426, in _run_node_sequential
    outputs = _call_node_run(
              ^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py", line 392, in _call_node_run
    raise exc
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py", line 382, in _call_node_run
    outputs = node.run(inputs)
              ^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\pipeline\node.py", line 357, in run
    raise exc
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\pipeline\node.py", line 350, in run
    outputs = self._run_with_dict(inputs, self._inputs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\pipeline\node.py", line 400, in _run_with_dict
    return self._func(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\Homework\S7\ASI\ASI\asi-03\src\asi_03\pipelines\training.py", line 31, in train
    model_name='KNN', feature_names=train_X.columns)
                                    ^^^^^^^^^^^^^^^
AttributeError: 'numpy.ndarray' object has no attribute 'columns'
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ in _run_module_as_main:198                                                                       │
│ in _run_code:88                                                                                  │
│                                                                                                  │
│ in <module>:7                                                                                    │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\cli\cli.py:211 in main │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py:1157 in __call__         │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\cli\cli.py:139 in main │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py:1078 in main             │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py:1688 in invoke           │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py:1434 in invoke           │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\click\core.py:783 in invoke            │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\cli\project.py:453 in  │
│ run                                                                                              │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\framework\session\session.py:436 │
│ in run                                                                                           │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py:103 in run      │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\sequential_runner.py:70   │
│ in _run                                                                                          │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py:331 in run_node │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py:426 in          │
│ _run_node_sequential                                                                             │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py:392 in          │
│ _call_node_run                                                                                   │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\runner\runner.py:382 in          │
│ _call_node_run                                                                                   │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\pipeline\node.py:357 in run      │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\pipeline\node.py:350 in run      │
│                                                                                                  │
│ C:\Users\User\anaconda3\envs\asi-03_env\Lib\site-packages\kedro\pipeline\node.py:400 in          │
│ _run_with_dict                                                                                   │
│                                                                                                  │
│ C:\Users\User\Desktop\Homework\S7\ASI\ASI\asi-03\src\asi_03\pipelines\training.py:31 in train    │
│                                                                                                  │
│   28 │   #plot_roc(test_Y, predicted_probability, pd.unique(train_Y))                            │
│   29 │   #plot_precision_recall(test_Y, predicted_probability, pd.unique(train_Y))               │
│   30 │   wandb.sklearn.plot_classifier(model, train_X, test_X, train_Y, test_Y, predicted, pr    │
│ > 31 │   │   │   │   │   │   │   │   │   │   │   │   │   │    model_name='KNN', feature_names    │
│   32 │                                                                                           │
│   33 │   pickle.dump(model, open('model.sav', 'wb'))                                             │
│   34 │   print("Model successfully saved")                                                       │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'numpy.ndarray' object has no attribute 'columns'